### ISSUE TITLE
Have you considered Clojurescript?

### ISSUE THREAD

**Issue by omarestrella** [ericlifka/rogue-chat#5]
Might solve the issues you've been having.

**Comment by ericlifka** [comment]
👍

**Comment by areese159** [comment]
We've discussed this issue throughly and have taken your suggestions to heart but at this time we do not want to use garbage language like Clojurescript.

**Comment by ericlifka** [comment]
Suddenly we love clojurescript now and have changed our minds.

**Comment by areese159** [comment]
It appears we are bipolar and decided once again that we are against clojurescript. Sorry about the confusion.

**Comment by omarestrella** [comment]
:rage3:
